# Generated by Django 3.2.8 on 2021-11-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20211024_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='observacões',
            new_name='observacoes',
        ),
    ]
